# vim: ft=tmux
set -g mode-style "fg=#eee8d5,bg=#181818"

set -g message-style "fg=#eee8d5,bg=#181818"
set -g message-command-style "fg=#eee8d5,bg=#181818"

set -g pane-border-style "fg=#4f4537"
set -g pane-active-border-style "fg=#b59e7d"

set -g status "on"
set -g status-interval 1
set -g status-justify "left"

set -g status-style "fg=#b59e7d,bg=#181818"
set -g status-bg "#181818"

set -g status-left-length "100"
set -g status-right-length "100"

set -g status-left-style NONE
set -g status-right-style NONE

set -g status-left '#[bold] [#S] │ '
set -g status-right '"#{host}" #[fg=#ffedcb]│ #[fg=#b59e7d]%H:%M #[fg=#ffedcb]│ #[fg=#b59e7d]%d-%b-%y '

setw -g window-status-format '#[fg=#b6a999] #I:#W '
setw -g window-status-current-format '#[fg=#ffedcb,bold] #I:#W '
