bind r source-file ~/.config/tmux/tmux.conf \; display "Config reloaded!"

unbind C-b
set -g prefix C-s
bind C-s send-prefix

set -g mouse on
set -g base-index 1
setw -g pane-base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# set -g @plugin 'egel/tmux-gruvbox'
# set -g @tmux-gruvbox 'dark256'
source ~/.config/tmux/statusline.conf

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
run '~/.tmux/plugins/tpm/tpm'
