# totally inspired (or copied lol) from https://github.com/martin-djakovic/dotfiles/

$font = JetBrainsMono Nerd Font
$font_size = 12

$bg = rgb(101010)
$bg_alt = rgb(252525)
$fg = rgb(f6f1ea)

$accent = rgb(afa193)
$text_start_x = 820

animations {
  enabled = false
}

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor = 
    color = rgb(0, 0, 0)
    blur_size = 1
    blur_passes = 4
    brightness = 0.2
}


# Welcome message
label {
  text = wake up, $USER.

  font_family = $font Bold
  font_size = $font_size
  color = $accent

  halign = left
  valign = center
  position = $text_start_x,137
}

# time
label {
    text = cmd[update:43200000] echo "<span foreground='##afa193'>date: </span>$(date +'%d %b, %a.' | awk '{print tolower($0)}')"

    font_size = $font_size
    font_family = $font
    color = $fg

    halign = left
    valign = center
    position = $text_start_x, 104
}

# time
label {
    text = cmd[update:3000] echo "<span foreground='##afa193'>time: </span>$(date +'%H:%M' | awk '{print tolower($0)}')"

    font_family = $font
    color = $fg
    font_size = $font_size

    halign = left
    valign = center
    position = $text_start_x, 79
}


# box
shape {
  size = 300, 119
  color = $bg
  position = 0,94
  halign = center
  valign = center
}

input-field {
    size = 300, 50
    rounding = 0
    outline_thickness = 0
    inner_color = $bg

    outer_color=$bg_alt
    check_color=$bg_alt
    fail_color=$bg_alt

    font_family = $font Bold
    font_color = $accent
    placeholder_text = password
    fail_text = authentication failed
    fade_on_empty = false

    dots_size = 0.20
    dots_text_format = *
    dots_spacing = 0.32

    position = 0, 0
    halign = center
    valign = center
}

label {
  text = cmd[update:3000] echo "<span foreground='##afa193'>key: </span>$LAYOUT[br-abnt]"

  font_family = $font
  font_size = $font_size
  
  position = $text_start_x, 54
  halign=left
  valign=center
}
