require("hyprland.monitors")
require("hyprland.bindings")
require("hyprland.ui")
require("hyprland.rules")
require("hyprland.permissions")
require("hyprland.autostart")
require("hyprland.input")
require("hyprland.env")
