$font = SF Compact Display Regular

general {
    hide_cursor = true
    grace = 0
}

background {
    monitor = 
    path = ~/Pictures/wallpapers/visionboard06.png
    blur_size = 1
    blur_passes = 4
    brightness = 0.2
}

# TIME
label {
    monitor = 
    text = $TIME
    font_family = SF Compact Display Semibold
    color = rgba(255, 255, 255, 0.6)
    font_size = 90
    position = 0, 330
    halign = center
    valign = center
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] date +"%A, %d %B %Y"
    color = rgba(255, 255, 255, 0.6)
    font_size = 15
    font_family = $font
    position = 0, 400
    halign = center
    valign = center
}

input-field {
    monitor =
    font_family = $font
    size = 500, 50
    outline_thickness = 0
    inner_color = rgba(0, 0, 0, 0) # no fill

    outer_color = rgba(0, 0, 0, 0.3) 45deg
    check_color=rgba(0, 0, 0, 0.3) 120deg
    fail_color=rgba(0, 0, 0, 0.3) 40deg

    font_color = rgb(230, 230, 250)
    fade_on_empty = true
    rounding = 1000000

    position = 0, -330
    halign = center
    valign = center
}
