require 'kickstart.plugins.guess-indent'
require 'kickstart.plugins.gitsigns'
require 'kickstart.plugins.which-key'
require 'kickstart.plugins.colorscheme'
require 'kickstart.plugins.todo-comments'
require 'kickstart.plugins.mini'
require 'kickstart.plugins.lualine'
require 'kickstart.plugins.telescope'
require 'kickstart.plugins.lspconfig'
require 'kickstart.plugins.formatting'
require 'kickstart.plugins.blink-cmp'
require 'kickstart.plugins.treesitter'
require 'kickstart.plugins.lint'
require 'kickstart.plugins.neo-tree'
require 'kickstart.plugins.autopairs'

require 'custom.plugins'
